// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"
	"judgeMore/biz/router/auth"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _verifyemailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logoutMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryuserinfoMw() []app.HandlerFunc {
	// your code...
	return auth.Auth(1)
}

func _updateuserinfoMw() []app.HandlerFunc {
	// your code...
	return auth.Auth(1)
}

func _refreshtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendemailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _emailMw() []app.HandlerFunc {
	// your code...
	return nil
}
