// Code generated by hertz generator.

package maintain

import (
	"context"
	"judgeMore/biz/pack"
	"judgeMore/biz/service"
	"judgeMore/pkg/errno"

	"github.com/cloudwego/hertz/pkg/app"
	maintain "judgeMore/biz/model/maintain"
)

// QueryCollege .
// @router /api/admin/colleges [GET]
func QueryCollege(ctx context.Context, c *app.RequestContext) {
	var err error
	var req maintain.QueryAllCollegeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(maintain.QueryAllCollegeResponse)
	collegeInfo, total, err := service.NewMaintainService(ctx, c).QueryColleges(req.PageNum, req.PageSize)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.CollegeList(collegeInfo, total)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// QueryMajorByCollegeId .
// @router /api/admin/majors [GET]
func QueryMajorByCollegeId(ctx context.Context, c *app.RequestContext) {
	var err error
	var req maintain.QueryMajorByCollegeIdRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(maintain.QueryMajorByCollegeIdResponse)
	majorInfo, total, err := service.NewMaintainService(ctx, c).QueryMajorByCollegeId(req.CollegeID, req.PageNum, req.PageSize)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.MajorList(majorInfo, total)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// UploadMajor .
// @router /api/admin/majors [POST]
func UploadMajor(ctx context.Context, c *app.RequestContext) {
	var err error
	var req maintain.UploadMajorRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(maintain.UploadMajorResponse)
	majorId, err := service.NewMaintainService(ctx, c).UploadMajor(req.MajorName, req.CollegeID)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.MajorID = majorId
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// UploadCollege .
// @router /api/admin/colleges [POST]
func UploadCollege(ctx context.Context, c *app.RequestContext) {
	var err error
	var req maintain.UploadCollegeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}
	resp := new(maintain.UploadCollegeResponse)
	collegeId, err := service.NewMaintainService(ctx, c).UploadCollege(req.CollegeName)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.CollegeID = collegeId
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}
