// Code generated by hertz generator.

package appeal

import (
	"github.com/cloudwego/hertz/pkg/app"
	"judgeMore/biz/router/auth"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return auth.Auth(1)
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _appealMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateappealstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteappealMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryappealinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _applyappealMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _appeal0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querystuappealinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}
