// Code generated by hertz generator.

package score

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _scoreMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryscorebyscoreidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryscorebyeventidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryscorebystuidMw() []app.HandlerFunc {
	// your code...
	return nil
}
