// Code generated by hertz generator.

package appeal

import (
	"context"
	"judgeMore/biz/pack"
	"judgeMore/biz/service"
	"judgeMore/biz/service/model"
	"judgeMore/pkg/errno"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	appeal "judgeMore/biz/model/appeal"
)

// ApplyAppeal .
// @router /api/upload/appeal [POST]
func ApplyAppeal(ctx context.Context, c *app.RequestContext) {
	var err error
	var req appeal.ApplyAppealRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "required file but found not "))
		return
	}
	a := &model.Appeal{
		AppealReason: req.AppealMessage,
		AppealType:   req.AppealType,
		ResultId:     req.ResultID,
	}
	if req.AttachmentPath != nil {
		a.AttachmentPath = *req.AttachmentPath
	}
	resp := new(appeal.ApplyAppealResponse)
	appeal_id, err := service.NewAppealService(ctx, c).NewAppeal(a)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.AppealID = appeal_id
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// DeleteAppeal .
// @router /api/delete/appeal [DELETE]
func DeleteAppeal(ctx context.Context, c *app.RequestContext) {
	var err error
	var req appeal.DeleteAppealRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "required file but found not "))
		return
	}

	resp := new(appeal.DeleteAppealResponse)
	err = service.NewAppealService(ctx, c).DeleteAppeal(req.AppealID)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}

	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// QueryAppealInfo .
// @router /api/query/appeal [GET]
func QueryAppealInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req appeal.QueryAppealInfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "required file but found not "))
		return
	}

	resp := new(appeal.QueryAppealInfoResponse)
	appealInfo, err := service.NewAppealService(ctx, c).QueryAppealById(req.AppealID)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.Appeal(appealInfo)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// UpdateAppealStatus .
// @router /api/appeal/status [POST]
func UpdateAppealStatus(ctx context.Context, c *app.RequestContext) {
	var err error
	var req appeal.UpdateAppealRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(appeal.UpdateAppealResponse)

	c.JSON(consts.StatusOK, resp)
}

// QueryStuAppealInfo .
// @router /api/query/appeal/stu [GET]
func QueryStuAppealInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req appeal.QueryStuAppealInfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "required file but found not "))
		return
	}

	resp := new(appeal.QueryStuAppealInfoResponse)
	appealInfo, count, err := service.NewAppealService(ctx, c).QueryStuAllAppeals()
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.AppealList(appealInfo, count)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}
