// Code generated by hertz generator.

package user

import (
	"context"
	"judgeMore/biz/mw/jwt"
	"judgeMore/biz/pack"
	"judgeMore/biz/service"
	"judgeMore/biz/service/model"
	"judgeMore/pkg/errno"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	user "judgeMore/biz/model/user"
)

// Register .
// @router /api/auth/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}
	resp := new(user.RegisterResponse)
	UserResp, err := service.NewUserService(ctx, c).Register(&model.User{
		UserName: req.Username,
		Password: req.Password,
		Email:    req.Email,
		Uid:      req.Id,
	})
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.UserID = UserResp
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)

}

// Login .
// @router /api/auth/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(user.LoginResponse)
	UserResp, err := service.NewUserService(ctx, c).Login(&model.User{
		Uid:      req.Id,
		Password: req.Password,
	})
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	jwt.AccessTokenJwtMiddleware.LoginHandler(ctx, c)
	jwt.RefreshTokenJwtMiddleware.LoginHandler(ctx, c)

	c.Header("Access-Token", c.GetString("Access-Token"))
	c.Header("Refresh-Token", c.GetString("Refresh-Token"))
	resp.Data = pack.User(UserResp)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// Logout .
// @router /api/auth/logout [POST]
func Logout(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LogoutReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.LogoutResp)

	c.JSON(consts.StatusOK, resp)
}

// VerifyEmail .
// @router /api/auth/email [POST]
func VerifyEmail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.VerifyEmailRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(user.VerifyEmailResponse)
	err = service.NewUserService(ctx, c).VerifyEmail(&model.EmailAuth{
		Email: req.Email,
		Code:  req.Code,
	})
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)

}

// QueryUserInfo .
// @router /api/users/ [GET]
func QueryUserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.QueryUserInfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(user.QueryUserInfoResponse)

	UserResp, err := service.NewUserService(ctx, c).QueryUserInfo(&model.User{
		Uid: req.Id,
	})
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.User(UserResp)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// UpdateUserInfo .
// @router /api/users/me [PUT]
func UpdateUserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UpdateUserInfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(user.UpdateUserInfoResponse)
	u := &model.User{}
	if req.Grade != nil {
		u.Grade = *req.Grade
	}
	if req.Major != nil {
		u.Major = *req.Major
	}
	if req.College != nil {
		u.College = *req.College
	}
	UserResp, err := service.NewUserService(ctx, c).UpdateUserInfo(u)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.User(UserResp)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// SendEmail .
// @router /api/update/user/password [POST]
func SendEmail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.SendEmailRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(user.SendEmailResponse)
	err = service.NewUserService(ctx, c).Email(&model.User{Email: req.Email})
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}

	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// UpdatePassword .
// @router /api/update/user/password [PUT]
func UpdatePassword(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UpdateUserPasswordRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(user.UpdateUserPasswordResponse)
	err = service.NewUserService(ctx, c).UpdateUserPassword(&model.User{Uid: req.UserID, Password: req.Password}, req.Code)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// RefreshToken .
// @router /api/auth/refresh [GET]
func RefreshToken(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RefreshTokenRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(user.RefreshTokenResponse)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}
