// Code generated by hertz generator.

package maintain

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querycollegeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadcollegeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querymajorbycollegeidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadmajorMw() []app.HandlerFunc {
	// your code...
	return nil
}
